### ISSUE TITLE
After Launching MAS, I am unable to update custom rooms from v1.01 to v1.02 using the submod updater plugin

### ISSUE THREAD

**Issue by delongr28** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#10]
MAS plays as per normal and the custom backgrounds do load in, I am just unable to update them from v1.01 to v1.02 using the submod updater plugin despite being notified there's an update.

![2](https://user-images.githubusercontent.com/16112887/94890456-ddb0b500-04b1-11eb-809a-e5c07cd3e689.png)

![3](https://user-images.githubusercontent.com/16112887/94890699-8c54f580-04b2-11eb-8881-e62199eebd03.png)

Here's the log I think it's talking about:
[log.txt](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/5316095/log.txt)

Or it's this one:
[mas_log.txt](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/5316100/mas_log.txt)

**Comment by Cdino11** [comment]
ill look into this, post this here as well https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/issues

**Comment by delongr28** [comment]
> ill look into this, post this here as well https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin/issues

OK. I have posted the issue there also.
