### ISSUE TITLE
I can't update the furnished spaceroom v1 v2 and v3 

### ISSUE THREAD

**Issue by Samu49** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#11]
I can't update these 3 the other can update but not these 3

![IMG_20201002_185138](https://user-images.githubusercontent.com/72270245/94948943-7100df00-04e0-11eb-84a8-0294eafce046.jpg)

**Comment by multimokia** [comment]
Say goodbye and upload your `log/mas_log.txt` please

**Comment by Samu49** [comment]
> Say goodbye and upload your `log/mas_log.txt` please

How do i upload ?

**Comment by multimokia** [comment]
Drag and drop it into the textbox

**Comment by Samu49** [comment]
> 
> 
> Drag and drop it into the textbox

[mas_log.txt](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/5319362/mas_log.txt)

**Comment by multimokia** [comment]
Send a screenshot of your `/game/submods/location_selector/locations` please

**Comment by Samu49** [comment]
> 
> 
> Send a screenshot of your `/game/submods/location_selector/locations` please

after location_selector i have locatons but not locations is that a glitch ?

**Comment by multimokia** [comment]
sorry, that's correct, inside the `locatons` folder

**Comment by Samu49** [comment]
![Uploading IMG_20201002_191412.jpg…]()
 
And sorry i'm french so it's hard to understand

**Comment by multimokia** [comment]
Might have to wait a little longer before commenting, the image didn't finish uploading

**Comment by Samu49** [comment]
> Il faudra peut-être attendre un peu plus longtemps avant de commenter, l'image n'a pas fini de télécharger

I edited sorry

**Comment by Samu49** [comment]
> Might have to wait a little longer before commenting, the image didn't finish uploading

![IMG_20201002_191412](https://user-images.githubusercontent.com/72270245/94951586-da82ec80-04e4-11eb-924a-8f09bc9b2d2c.jpg)

(Just in case)

**Comment by Samu49** [comment]
Did you found something ?

**Comment by Samu49** [comment]
> 
> 
> Might have to wait a little longer before commenting, the image didn't finish uploading

did you found something ?

**Comment by multimokia** [comment]
I'm thinking it might be an issue with OneDrive.

You'll probably want to disable it for your MAS install. It's known to cause issues.

**Comment by Samu49** [comment]
> 
> 
> I'm thinking it might be an issue with OneDrive.
> 
> You'll probably want to disable it for your MAS install. It's known to cause issues.

i already disable it

**Comment by multimokia** [comment]
Looking at your screenshots, it's still enabled for the folder. The filepath also seems to indicate that as `OneDrive` is part of the filepath.

**Comment by Samu49** [comment]
> 
> 
> Looking at your screenshots, it's still enabled for the folder. The filepath also seems to indicate that as `OneDrive` is part of the filepath.

what can i do ?

**Comment by Samu49** [comment]
> 
> 
> Looking at your screenshots, it's still enabled for the folder. The filepath also seems to indicate that as `OneDrive` is part of the filepath.

yes but i updated the other one with no problem

**Comment by Samu49** [comment]
> 
> 
> Looking at your screenshots, it's still enabled for the folder. The filepath also seems to indicate that as `OneDrive` is part of the filepath.

the mas_log.txt say something else now
[mas_log.txt](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/5319910/mas_log.txt)

**Comment by Samu49** [comment]
> Looking at your screenshots, it's still enabled for the folder. The filepath also seems to indicate that as `OneDrive` is part of the filepath.

So what can i do please

**Comment by multimokia** [comment]
Honestly I'm not too sure. onedrive is tricky. Regardless you can just manually update these ones.

**Comment by Samu49** [comment]
> Honnêtement, je ne suis pas trop sûr. onedrive est délicat. Quoi qu'il en soit, vous pouvez simplement les mettre à jour manuellement.

And how i can do that ?

**Comment by multimokia** [comment]
By downloading the latest release and installing it like you first installed the submod.

**Comment by Samu49** [comment]
> By downloading the latest release and installing it like you first installed the submod.

Can you give me a link where i can download them ?

**Comment by Samu49** [comment]
Nevermind i found how to update them manually sorry to bother you
