### ISSUE TITLE
Monika saying when she's good at programming i'll make a kitchen

### ISSUE THREAD

**Issue by Ant9cp** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#12]
So when you ask monika to do a impression of natsuki she talks later about programming a kitchen and sharing some recipes with her so since there's a submod for different furniture/rooms, there is also a kitchen included but she doesn't mention anything.

**Comment by Cdino11** [comment]
ah thank you for letting us know, this will be fixed in the next hotfix release
