### ISSUE TITLE
(Question) About how this submod effects on holidays and other events

### ISSUE THREAD

**Issue by Ant9cp** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#13]
When it's like on halloween or christmas or birthdays how will this submod affect on them?

Is there going to be decorations in every room automatically?

**Comment by tw4449** [comment]
It already works with birthdays, and we will be adding functionality for Halloween in an update this month, and for Christmas in an update in December.

**Comment by tw4449** [comment]
And yes, we will be adding decor for each room separately.

**Comment by Ant9cp** [comment]
Thanks for letting me know 👍

**Comment by tw4449** [comment]
No problem.
