### ISSUE TITLE
(Suggestion) Topic's about the new rooms and items in the rooms

### ISSUE THREAD

**Issue by Ant9cp** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#14]
Something for monika to talk about of the new rooms and the items

**Comment by Cdino11** [comment]
what did you have in mind?

**Comment by Ant9cp** [comment]
Topic 1(Similar Kitchen) Hey (name) the kitchen look so similar like the one in the school but without the green wall, this reminds me of something before you joined the literature club. When it was the festival every club president needs to participate in other clubs in the school, and as time was passing by i got thirsty and i went to the kitchen to get some water when i looked around the kitchen i just got lost in my thoughts, it is such a beautiful kitchen. (Jealous expression) haha sorry (name) i guess i'm a little bit jealous about the kitchen the school has. Anyway thank you so much for adding a kitchen (name) this kitchen just looks like the one in the school.
