### ISSUE TITLE
Question about custom rooms being disabled on october 31st?

### ISSUE THREAD

**Issue by Ant9cp** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#16]
So i ask this in #13 and now, since i went to go update the submod i read in the latest update of this mod that the extra rooms is 
gonna be disabled in october 31st i'm confused?

**Comment by Samu49** [comment]
yeah i'm confused too that mean we can't use it anymore after the 31 oct ?

**Comment by tw4449** [comment]
The MAS devs were unable to add functionality that allows custom decor in submodded rooms. Therefore, they decided to disable custom rooms for Halloween (only).

**Comment by Samu49** [comment]
So that mean there will be an update the 31oct ? Or we just can't use the custom rooms for halloween ?

**Comment by tw4449** [comment]
The appropriate code was added in the official MAS update this week as well as the update my team put out. If you have both updates, it will work correctly. You will just not be able to use custom rooms on Halloween.

**Comment by Samu49** [comment]
Ho ok i was a bit worried thanks for the help
