### ISSUE TITLE
Cant update to 1.0.3

### ISSUE THREAD

**Issue by Marmarkarp** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#17]
I tried everything but three specific rooms refuse to update for me. I'll show pics rn and this is all I see. I would really like some help 
![screenshot0005](https://user-images.githubusercontent.com/73798650/97815779-893e5800-1c5e-11eb-957d-ed91997e2526.png)
[](![screenshot0006](https://user-images.githubusercontent.com/73798650/97815860-1c778d80-1c5f-11eb-8cce-9b390c79e9f7.png))

[submod_log.txt](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/5471796/submod_log.txt)
[mas_log.txt](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/5471797/mas_log.txt)

**Comment by Cdino11** [comment]
How are you running MAS

**Comment by Marmarkarp** [comment]
I'm running it on pc, not on steam

**Comment by Cdino11** [comment]
It may not be the only problem but running through one drive seems to cause problems, but a quick fix is to download them manually either from this repository or from Their own individual ones

**Comment by Marmarkarp** [comment]
I tried downloading them one by one but the error keeps popping up

**Comment by Cdino11** [comment]
What error, you should not be getting an error if you are downloading them from the web page

**Comment by Marmarkarp** [comment]
Oh I misunderstood. So I download from the webpage indivually and put it into the ddlc folder? I don't really understand I'm sorry

**Comment by Cdino11** [comment]
its your choice whether you want to download them all or individually from the webpage. i was just leaving suggestions. either way to fix your problem download them manually so you have the most current version of each room. 

here is a link to the all in one https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository
here is a to v1 https://github.com/tw4449/Custom-Room-Furnished-Spaceroom-V1
v2 https://github.com/tw4449/Custom-Room-Furnished-Spaceroom-V2
v3 https://github.com/tw4449/Custom-Room-Furnished-Spaceroom-V3
