### ISSUE TITLE
possible bug?

### ISSUE THREAD

**Issue by opalmew** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#18]
when i have spaceroom v3 selected and i shrink the tab, outside the windows is black rather than whatever the weather is supposed to be when i open back up the tab. is this a bug, or did i download the submod incorrectly?

**Comment by Cdino11** [comment]
i believe this is a bug on MAS side. I am unable to replicate it/ this is the first time heard of this problem, especially since it happens when you shrink the game. to get better help with it please leave this issue here https://github.com/Monika-After-Story/MonikaModDev/issues
