### ISSUE TITLE
Error updating mod for Spaceroom v3, log not helping

### ISSUE THREAD

**Issue by Outlander676** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#21]
Basically what I said in the title, it says to check the log for further details but there's nothing out of the ordinary there. Any help would be much appreciated.

Or does it mean log.txt in the updates folder? I have something in there, says 'partfile does not exist' whatever that means

**Comment by tw4449** [comment]
Could you leave a screenshot of the crash log?
