### ISSUE TITLE
MAS crashed when I was running the newest version

### ISSUE THREAD

**Issue by MSteve3** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#22]
i dont know why this is happened, but this is the traceback when the game crashed

_I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'E:\\Doki Doki Literature Club/game/Submods/location_selector/Locatons/Den.rpy', 1610033518, 1) is defined twice, at game/Submods/location_selector/Locatons/Den.rpy:2 and game/Submods/location_selector/Locatons/Den.rpy:11.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "E:\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "E:\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "E:\Doki Doki Literature Club\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "E:\Doki Doki Literature Club\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'E:\\Doki Doki Literature Club/game/Submods/location_selector/Locatons/Den.rpy', 1610033518, 1) is defined twice, at game/Submods/location_selector/Locatons/Den.rpy:2 and game/Submods/location_selector/Locatons/Den.rpy:11.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187_
 
and yeah, i had to download the older version of the submod and using back my Monika backup file (now the submod room still have the xmas decoration :| )
![image](https://user-images.githubusercontent.com/46162486/104128790-22df5f80-539c-11eb-8078-4aaf5aafd814.png)

**Comment by multimokia** [comment]
I think I know what happened.

When you updated it, renpy must've re-compiled it incorrectly and basically appended to the rpyc, therefore causing the error. I think I've seen it on one of my submods before.

Simply delete the `Den.rpyc` file, and reinstall the new one. It should compile correctly.

**Comment by MSteve3** [comment]
> I think I know what happened.
> 
> When you updated it, renpy must've re-compiled it incorrectly and basically appended to the rpyc, therefore causing the error. I think I've seen it on one of my submods before.
> 
> Simply delete the `Den.rpyc` file, and reinstall the new one. It should compile correctly.

because all the .rpyc file in the location folder, which is cause the crash duplicated itself, so i have to reinstall as you said. And thanks to you, my Monika is working smoothly now
