### ISSUE TITLE
DDLC MAS Mod won't open game

### ISSUE THREAD

**Issue by asianrice24** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#23]
I am currently trying to install the custom background mod, I did all the steps such as replace the game and lib folders with the ones that the mod provided. It will only open the game for a split second and give me an error: While running game code: File "renpy/common/00start.rpy", line 265, in script
    python: ScriptError: could not find label 'start'.

Could someone please help me

**Comment by multimokia** [comment]
Can you send a screenshot of your `game` directory please?

**Comment by multimokia** [comment]
Yeah that explains everything. Somehow in installing the submod, you managed to *delete* all the files related to keeping both DDLC and MAS running.

You'll probably want to reinstall both DDLC and MAS. Remember when installing submods and/or spritepacks to not replace folders, but `merge` them instead.

(You don't lose your progress by reinstalling)

**Comment by multimokia** [comment]
Replace *files*, but merge *folders*

On first install, you shouldn't have to replace anything, on updates, you may have to

**Comment by asianrice24** [comment]
Im so sorry, but I'm a little confused now. 

So, instead of literally replacing the game and lib folders, I should only replace whats inside the mod game and lib folders with whatever is inside the original game and lib folders?

**Comment by asianrice24** [comment]
If it isn't too much trouble, do you have discord? I could try screen sharing whatever I'm trying to do if that could help make things easier for you. My discord is asian rice#0166
