### ISSUE TITLE
Monika noticed the files, but she tells me she can't program that in just yet.

### ISSUE THREAD

**Issue by CrewieAustin** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#24]
After dropping the files in, Monika told me she noticed I've added the furniture. But she told me she can't code in just yet. She tells me she will notify me once she knows how to do it.. ?? Is this suppose to be a glitch or I don't have enough affection points yet ?

**Comment by tw4449** [comment]
It means you don’t have enough affection yet. It’s working properly. The rooms will activate at 400 affection.
