### ISSUE TITLE
Is it normal ?

### ISSUE THREAD

**Issue by Samu49** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#28]
I did the new update correctly as always but is it normal that everything is still 1.0.5 and not 1.0.5.2 ?

**Comment by Cdino11** [comment]
Yes it was just a small update only for the submod updater so new people who download it have the most recent version. The version stays the same so it dosent push and update to people who already have it downloaded.

**Comment by Samu49** [comment]
Ok thanks for the quick response.
