### ISSUE TITLE
help please duplicate files 

### ISSUE THREAD

**Issue by Ohkanzo** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#5]
![Submod Updater Plugin 9_14_2020 10_45_13 PM](https://user-images.githubusercontent.com/71305672/93163137-f8c2ad00-f6db-11ea-8f72-c838df0a91c7.png)

![traceback txt - Notepad 9_14_2020 10_41_34 PM](https://user-images.githubusercontent.com/71305672/93162954-85b93680-f6db-11ea-95f3-384e0b7dd2c7.png)
 so when I go to update the sub mod it will add another "sub mod updater plugin" forcing my game to crash and every time I delete the duplicate it just pops back in when I launch the game

**Comment by Cdino11** [comment]
oh i see it now. its an issue with one drive. that's also why it keeps coming back

**Comment by Ohkanzo** [comment]
how do i fix it?

**Comment by Ohkanzo** [comment]
> oh i see it now. its an issue with one drive. that's also why it keeps coming back
uh how do i fix it?

**Comment by Cdino11** [comment]
give us a bit we are looking into it. you also have two game folders and that is likely another problem, you should only have 1. delete the copies again and make sure you only have 1 game folder

**Comment by Ohkanzo** [comment]
ok uh the 2nd game folder has all the sub mods in it just rename it?

**Comment by Cdino11** [comment]
yes, the best thing you can do to group your submods is to keep them in a folder named Submods and have that in the game folder. having multiple game folders causes problems 

your file path to the submods folder should look like this 

*DDLC-1.1.1-pc(or whatever you named it. this is the folder with ddlc.exe in it) 

DDLC-1.1.1-pc/game/Submods

**Comment by Ohkanzo** [comment]
I think I got it is v1.4 the latest?

**Comment by Cdino11** [comment]
yes

**Comment by Ohkanzo** [comment]
ok then i got it to work thanks for the help!!

**Comment by Cdino11** [comment]
no problem, if there are any more problems let us know. enjoy!
