### ISSUE TITLE
Multiple "defined twice" labels when the entire pack is downloaded and used

### ISSUE THREAD

**Issue by DarkDawnzenith** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#8]
So, there's this error right here when I've downloaded the entire pack and tried to play MAS with all of them.

[errors.txt](https://github.com/tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository/files/5264680/errors.txt)

And the only way to fix this issue is to give each script file an unique label so this error doesn't show up for new people who's about to try this pack.

**Comment by d3adpan** [comment]
Have you updated to the most recent release, and is the trouble still happening?
