### ISSUE TITLE
it wont update for some reason

### ISSUE THREAD

**Issue by AnIdiotsavant** [tw4449/tw4449-Custom-Room-Selection-Pack-Main-Repository#9]
It hasn't been updating. Sometimes only 1 part like the den can be updated but other than that its always an error. It said to check the logs, maybe you guys could help me understand what to fix in my MAS?

Sun Sep 27 22:27:19 2020
Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.11.5

VERSION: 0.11.5
[SUBMOD UPDATER PLUGIN ERROR]: Failed to request JSON data. Exception: HTTP Error 404: Not Found
[SUBMOD UPDATER PLUGIN ERROR]: Failed to request JSON data. Exception: HTTP Error 404: Not Found
[SUBMOD UPDATER PLUGIN ERROR]: Failed to move update files. Exceptions:
[Error 5] Access is denied: u"C:/Users/Shaun/3D Objects/Josh's files/Josh/DDLC-1.1.1-pc/lib/windows-i686/Lib/_ssl.pyd"
[SUBMOD UPDATER PLUGIN REPORT]: Downloaded and installed the 1.0.2 update for 'Custom Room Den'.
[SUBMOD UPDATER PLUGIN ERROR]: Failed to extract update. Exception: [Errno 2] No such file or directory: u"C:\\Users\\Shaun\\3D Objects\\Josh's files\\Josh\\DDLC-1.1.1-pc\\game\\Submods\\location_selector\\Locatons\\temp_custom_room_furnished_spaceroom_v1_1601216971\\tw4449-Custom-Room-Furnished-Spaceroom-V1-cb95449\\game\\Submods\\Submod Updater Plugin\\indicator_update_available.png"
[SUBMOD UPDATER PLUGIN ERROR]: F

I can move rooms frequently though but I'm just a bit puzzled why updating doesn't work

**Comment by d3adpan** [comment]
Are you running the game from the .zip or is it installed on your machine?

**Comment by Cdino11** [comment]
this is a problem we are looking into

**Comment by Cdino11** [comment]
we need the full error log if you can recreate it
